name: Playwright General Test

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  general-test:
    if: contains(github.event.head_commit.message, 'gtest')
    runs-on: ubuntu-latest
    container:
      # 公式のPlaywrightイメージを使用x
      image: mcr.microsoft.com/playwright:v1.51.1-jammy

    env:
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # GitHub Actionsのキャッシュを設定
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: tests/e2e-tests/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('tests/e2e-tests/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 依存関係をインストール
      - name: Install dependencies
        run: npm ci
        working-directory: tests/e2e-tests

      # 7. storage state 保存用ディレクトリ作成
      - name: Prepare auth directory
        run: mkdir -p playwright/.auth
        working-directory: tests/e2e-tests

      # 8. 認証用 setup プロジェクト実行
      - name: Run Playwright auth setup
        run: npx playwright test --project=setup --config=playwright.config.js
        working-directory: tests/e2e-tests

      - name: Run Playwright tests
        run:
          #npx playwright test tests/e2e-tests/tests/unauthenticated/menu.spec.js \
          npx playwright test tests/e2e-tests/tests/main/customiser.spec.ts \
          --project=main \
          --config=playwright.config.js
          --reporter=list
        working-directory: tests/e2e-tests

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: tests/e2e-tests/test-results/
